### ISSUE TITLE
Support oneOf/anyOf in graphql schema generation

### ISSUE THREAD

**Issue by dfeyer** [thenativeweb/wolkenkit#1157]
### What is this bug about?

Based on https://github.com/thenativeweb/wolkenkit/blob/393d6687a693d2e3b3983b004130aff459d1ebf6/lib/apis/graphql/v2/handleCommand/getCommandFieldConfiguration.ts#L54 if a type object, with oneOf/anyOf (so no direct `properties`) this code will break.

### What is the expected result?

Support oneOf correctly

### What is the actual result?

Exception

```
12:28:57.963@2020-07-29 3696774#1
{
  ex: {
    name: 'TypeError',
    message: 'Cannot convert undefined or null to object',
    stack: 'TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.getCommandFieldConfiguration (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/handleCommand/getCommandFieldConfiguration.js:25:46)
    at Object.getAggregateFieldConfiguration (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/handleCommand/getAggregateFieldConfiguration.js:9:84)
    at Object.getContextFieldConfiguration (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/handleCommand/getContextFieldConfiguration.js:9:86)
    at Object.getSendCommandFieldConfiguration (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/handleCommand/getSendCommandFieldConfiguration.js:9:82)
    at Object.getMutationSchema (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/handleCommand/getMutationSchema.js:11:57)
    at Object.getSchema (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/getSchema.js:12:60)
    at Object.getV2 (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/v2/index.js:25:56)
    at async Object.getApi (authoring-tool-store/node_modules/wolkenkit/build/lib/apis/graphql/index.js:11:16)
    at async Object.getApi (authoring-tool-store/node_modules/wolkenkit/build/lib/runtimes/singleProcess/processes/main/getApi.js:66:103)'
  }
}
```

**Comment by dfeyer** [comment]
Based on the README https://github.com/thenativeweb/get-graphql-from-jsonschema#knowing-the-limitations ... look like I hit a limitation ... but in this case is it possible to have all the graphql stuff optional ? We have quiet a few schema that needs `oneOf` ... and we will not use GraphQL (or we can live without it)

**Comment by yeldiRium** [comment]
We use our package [get-graphql-from-jsonschema](https://www.npmjs.com/package/get-graphql-from-jsonschema) to convert json schemas to GraphQL schemas.

While researching your issue, I noticed a misconception in the package and fixed that as well as added some documentation. The readme now contains a section on the use of `oneOf`:

The `oneOf` keyword is supported with a limitation on its use: There must be no other properties on the same level as the `oneOf`.

```javascript
const { typeName, typeDefinitions } = getGraphqlFromJsonSchema({
  rootName: 'foobar',
  schema: {
    oneOf: [
      {
        type: 'number'
      },
      {
        type: 'object',
        properties: {
          foo: { type: 'string' },
          bar: { type: 'number' }
        },
        required: [ 'foo' ],
        additionalProperties: false
      }
    ]
  }
});

console.log(typeName);
// => Foobar

console.log(typeDefinitions);
// => [
//     'type FoobarI1T0 {
//       foo: String!
//       bar: Float
//     }',
//     'union Foobar = Float | FoobarI1T0'
// ]
```

Also:

`The keywords `allOf` and `anyOf` get ignored, since their logic can not be mapped to GraphQL.`

The new, fixed version of `get-graphql-from-jsonschema` will be included in the next wolkenkit ctp release, which will probably be published today.

Does that solve your issue?

**Comment by goloroden** [comment]
@dfeyer Can you please try `wolkenkit@4.0.0-internal.64` and see whether this resolves your issue?

**Comment by dfeyer** [comment]
I will do that later today and let you know if it fix my issue

**Comment by goloroden** [comment]
@dfeyer Any update on this?

**Comment by goloroden** [comment]
No feedback received, hence closed.
